### ISSUE TITLE
Rendering item doesn't show in IE11

### ISSUE THREAD

**Issue by ShahriatHossain** [vickramravichandran/angular-auto-complete#23] opened 2018-06-04 11:02 UTC
Rendering item doesn't render in IE11, I am using following chunk of code:

```
renderItem: function (item) {
                return {
                    value: item.Name,
                    label: "<p class='auto-complete' ng-bind-html='entry.item.Name'></p>"
                };
            }
```

It seems that following html code `<p class='auto-complete' ng-bind-html='entry.item.Name'></p>` shows in all other browser except internet explorer 11.

[Note: When selecting from blank list the item is showing on selected item but not showing item name in the drop down  auto suggestion list.]

What could be the reason? Any suggestion?

**Comment by vickramravichandran** [comment] 2018-06-04 12:09
Can you create a Plunkr?

Here is a working sample. Try it in IE 11 https://codepen.io/vickramravichandran/pen/rKxqGm

**Comment by vickramravichandran** [comment] 2018-06-04 13:39
Can you reinstall the npm package and try again. There was an issue with the way it was published to npm. Better do uninstall and install.

**Comment by ShahriatHossain** [comment] 2018-06-05 10:37
@vickramravichandran The problem is resolved by replacing "parentNode" with "parentElement" in angular-auto-complete.js file. Because IE 11 doesn't recognize "parentNode"  but other browsers do.

**Comment by vickramravichandran** [comment] 2018-06-05 11:22
IE11 definitely supports "parentNode". Here is a screenshot of Developer Toolbar in IE11 with breakpoint. It clearly proves "parentNode" works in IE11.

![image](https://user-images.githubusercontent.com/2133516/40973334-e749e2bc-6891-11e8-8e48-272e2f88f76b.png)

![image](https://user-images.githubusercontent.com/2133516/40972999-a381cf1e-6890-11e8-8669-eb4119828e94.png)

All the samples in my [demo site](http://demo.vickram.me/angular-auto-complete/) work in IE11. I think its something else. Did you try my [CodePen](https://codepen.io/vickramravichandran/pen/rKxqGm) link in IE11 from your machine?

**Comment by ShahriatHossain** [comment] 2018-06-06 05:38
@vickramravichandran yes parentNode still works, so here is my below updated code which works in IE 11:

$(element[0].parentElement?element[0].parentElement:element[0].parentNode).append(clonedElement);

**Comment by vickramravichandran** [comment] 2018-06-06 12:10
Okay then, I am closing this issue since I cannot reproduce it. I tested this on few machines at home and work but was unable to reproduce the issue you are having. It works in IE 11 without any code changes as seen in the screenshot in my comment earlier.

**Closed as completed by vickramravichandran** 2018-06-06 12:10 UTC
Labels: bug, cannot reproduce
